let productArr = [
  {
    productName: "Licensed Rubber Hat",
    productPrice: "870.00",
    productSize: [8, 9, 10],
    productQuantity: "PL",
    productCode: "MOP",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "1",
  },
  {
    productName: "Sleek Frozen Salad",
    productPrice: "732.00",
    productSize: [8, 9, 10],
    productQuantity: "BF",
    productCode: "XBA",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "2",
  },
  {
    productName: "Bespoke Wooden Fish",
    productPrice: "523.00",
    productSize: [8, 9, 10],
    productQuantity: "IS",
    productCode: "SRD",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "3",
  },
  {
    productName: "Recycled Frozen Gloves",
    productPrice: "858.00",
    productSize: [8, 9, 10],
    productQuantity: "AE",
    productCode: "KYD",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "4",
  },
  {
    productName: "Refined Metal Chair",
    productPrice: "532.00",
    productSize: [8, 9, 10],
    productQuantity: "ZM",
    productCode: "CDF",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "5",
  },
  {
    productName: "Handmade Frozen Chair",
    productPrice: "196.00",
    productSize: [8, 9, 10],
    productQuantity: "NI",
    productCode: "TMT",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "6",
  },
  {
    productName: "Rustic Cotton Ball",
    productPrice: "317.00",
    productSize: [8, 9, 10],
    productQuantity: "NP",
    productCode: "MZN",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "7",
  },
  {
    productName: "Bespoke Frozen Soap",
    productPrice: "234.00",
    productSize: [8, 9, 10],
    productQuantity: "ZA",
    productCode: "FJD",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "8",
  },
  {
    productName: "Fantastic Steel Computer",
    productPrice: "131.00",
    productSize: [8, 9, 10],
    productQuantity: "BS",
    productCode: "SEK",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "9",
  },
  {
    productName: "Practical Soft Towels",
    productPrice: "94.00",
    productSize: [8, 9, 10],
    productQuantity: "KW",
    productCode: "HKD",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "10",
  },
  {
    productName: "Elegant Bronze Computer",
    productPrice: "55.00",
    productSize: [8, 9, 10],
    productQuantity: "MK",
    productCode: "WST",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "11",
  },
  {
    productName: "Awesome Rubber Chair",
    productPrice: "3.00",
    productSize: [8, 9, 10],
    productQuantity: "IT",
    productCode: "VUV",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "12",
  },
  {
    productName: "Recycled Soft Chair",
    productPrice: "118.00",
    productSize: [8, 9, 10],
    productQuantity: "DK",
    productCode: "GYD",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "13",
  },
  {
    productName: "Ergonomic Metal Chicken",
    productPrice: "604.00",
    productSize: [8, 9, 10],
    productQuantity: "LS",
    productCode: "LRD",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "14",
  },
  {
    productName: "Rustic Soft Chips",
    productPrice: "165.00",
    productSize: [8, 9, 10],
    productQuantity: "PE",
    productCode: "RWF",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "15",
  },
  {
    productName: "Elegant Frozen Chips",
    productPrice: "436.00",
    productSize: [8, 9, 10],
    productQuantity: "OM",
    productCode: "RWF",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "16",
  },
  {
    productName: "Handcrafted Soft Towels",
    productPrice: "237.00",
    productSize: [8, 9, 10],
    productQuantity: "KM",
    productCode: "CHF",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "17",
  },
  {
    productName: "Practical Concrete Car",
    productPrice: "358.00",
    productSize: [8, 9, 10],
    productQuantity: "CM",
    productCode: "UGX",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "18",
  },
  {
    productName: "Licensed Rubber Pants",
    productPrice: "678.00",
    productSize: [8, 9, 10],
    productQuantity: "SI",
    productCode: "VUV",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "19",
  },
  {
    productName: "Refined Frozen Salad",
    productPrice: "336.00",
    productSize: [8, 9, 10],
    productQuantity: "CH",
    productCode: "SEK",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "20",
  },
  {
    productName: "Handmade Soft Chips",
    productPrice: "194.00",
    productSize: [8, 9, 10],
    productQuantity: "EC",
    productCode: "PKR",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "21",
  },
  {
    productName: "Handmade Bronze Chips",
    productPrice: "448.00",
    productSize: [8, 9, 10],
    productQuantity: "BE",
    productCode: "RSD",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "22",
  },
  {
    productName: "Handmade Steel Gloves",
    productPrice: "415.00",
    productSize: [8, 9, 10],
    productQuantity: "AT",
    productCode: "HUF",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "23",
  },
  {
    productName: "Electronic Steel Bike",
    productPrice: "4.00",
    productSize: [8, 9, 10],
    productQuantity: "BL",
    productCode: "SRD",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "24",
  },
  {
    productName: "Bespoke Frozen Bacon",
    productPrice: "356.00",
    productSize: [8, 9, 10],
    productQuantity: "TT",
    productCode: "TWD",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "25",
  },
  {
    productName: "Unbranded Metal Computer",
    productPrice: "805.00",
    productSize: [8, 9, 10],
    productQuantity: "IN",
    productCode: "MMK",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "26",
  },
  {
    productName: "Intelligent Plastic Bacon",
    productPrice: "545.00",
    productSize: [8, 9, 10],
    productQuantity: "ME",
    productCode: "ARS",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "27",
  },
  {
    productName: "Sleek Fresh Mouse",
    productPrice: "336.00",
    productSize: [8, 9, 10],
    productQuantity: "VI",
    productCode: "SLL",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "28",
  },
  {
    productName: "Gorgeous Fresh Cheese",
    productPrice: "104.00",
    productSize: [8, 9, 10],
    productQuantity: "TO",
    productCode: "XPD",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "29",
  },
  {
    productName: "Sleek Steel Bacon",
    productPrice: "974.00",
    productSize: [8, 9, 10],
    productQuantity: "SO",
    productCode: "XPT",
    productImg: "https://loremflickr.com/640/480/sports",
    productID: "30",
  },
];
const productDB = JSON.parse(localStorage.getItem("productList"));
if (!productDB) {
  localStorage.setItem("productList", JSON.stringify(productArr));
}
